[project]
name = "ibis-overturemaps-tutorial"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.1.1",
    "ibis-framework[duckdb,geospatial]>=9.5.0",
    "jupyter>=1.1.1",
    "lonboard>=0.9.3",
]
